-- 1. Add monto_pagado to pedidos
alter table pedidos 
add column if not exists monto_pagado numeric default 0;

-- 2. Create pagos_recibidos table for traceability
create table if not exists pagos_recibidos (
    id bigint generated by default as identity primary key,
    cliente_id bigint references clientes(id) on delete cascade,
    monto numeric not null check (monto > 0),
    fecha timestamp with time zone default now(),
    descripcion text,
    metodo_pago_id bigint references medios_pago(id) on delete set null,
    created_at timestamp with time zone default now(),
    created_by uuid references auth.users(id)
);

-- 3. Add RLS for security
alter table pagos_recibidos enable row level security;

create policy "Enable read access for authenticated users"
on pagos_recibidos for select
to authenticated
using (true);

create policy "Enable insert access for authenticated users"
on pagos_recibidos for insert
to authenticated
with check (true);
