create table if not exists transferencias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null,
  origen_id bigint references medios_pago(id),
  destino_id bigint references medios_pago(id),
  valor numeric not null,
  descripcion text,
  usuario_id uuid references auth.users(id)
);

-- RLS Policies
alter table transferencias enable row level security;

create policy "Enable read access for authenticated users" on transferencias for select using (auth.role() = 'authenticated');
create policy "Enable insert access for authenticated users" on transferencias for insert with check (auth.role() = 'authenticated');
create policy "Enable update access for authenticated users" on transferencias for update using (auth.role() = 'authenticated');
create policy "Enable delete access for authenticated users" on transferencias for delete using (auth.role() = 'authenticated');
