
-- Create junction table to track exactly which orders a payment covered
CREATE TABLE IF NOT EXISTS pagos_pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT REFERENCES pagos_recibidos(id) ON DELETE CASCADE,
    pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE,
    monto DECIMAL(12, 2) NOT NULL CHECK (monto > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add Indexes for performance
CREATE INDEX IF NOT EXISTS idx_pagos_pedidos_pago ON pagos_pedidos(pago_id);
CREATE INDEX IF NOT EXISTS idx_pagos_pedidos_pedido ON pagos_pedidos(pedido_id);

-- RLS Policies
ALTER TABLE pagos_pedidos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for authenticated users" ON pagos_pedidos
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
