-- Arepas Factory ERP Schema

-- Enable UUID extension if needed, though Serial/Integer is fine for this scale, 
-- user requested "prepared for future growth", UUID is safer for distributed/large scale, 
-- but integer is easier for "human" usage (Order #123). 
-- I will use BIGINT GENERATED BY DEFAULT AS IDENTITY for compatibility and ease of use.

-- 1. CLIENTES
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    tipo_cliente TEXT NOT NULL CHECK (tipo_cliente IN ('mayorista', 'minorista', 'local', 'distribuidor')),
    telefono TEXT,
    direccion TEXT,
    ciudad TEXT DEFAULT 'Bogotá',
    canal_venta TEXT CHECK (canal_venta IN ('whatsapp', 'local', 'domicilio')),
    condicion_pago TEXT CHECK (condicion_pago IN ('contado', 'credito')) DEFAULT 'contado',
    cupo_credito DECIMAL(12, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. PROVEEDORES
CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    tipo_insumo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. PRODUCTOS
CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    codigo_corto TEXT UNIQUE NOT NULL, -- r, n, ch, qp, etc.
    tipo_producto TEXT CHECK (tipo_producto IN ('arepa', 'queso', 'otro')),
    precio_estandar DECIMAL(10, 2) NOT NULL,
    costo_unitario DECIMAL(10, 2) NOT NULL,
    unidad_medida TEXT NOT NULL, -- unidad, paquete, libra
    activo BOOLEAN DEFAULT TRUE,
    proveedor_id BIGINT REFERENCES proveedores(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. PRECIOS POR CLIENTE
CREATE TABLE precios_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    precio_especial DECIMAL(10, 2) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(cliente_id, producto_id) -- Prevent duplicate rules for same pair
);

-- 10. MEDIOS DE PAGO
CREATE TABLE medios_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL, -- Nequi, Daviplata, Efectivo
    tipo TEXT CHECK (tipo IN ('digital', 'efectivo', 'transferencia')),
    activo BOOLEAN DEFAULT TRUE
);

-- 4. PEDIDOS
CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id),
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total DECIMAL(12, 2) NOT NULL DEFAULT 0,
    medio_pago_id BIGINT REFERENCES medios_pago(id),
    estado TEXT CHECK (estado IN ('pendiente', 'pagado', 'parcial', 'cancelado')) DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. DETALLE PEDIDO
CREATE TABLE detalle_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id),
    cantidad INT NOT NULL,
    precio_aplicado DECIMAL(10, 2) NOT NULL, -- Snapshotted price
    subtotal DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. GASTOS
CREATE TABLE gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto TEXT NOT NULL,
    categoria TEXT CHECK (categoria IN ('materia_prima', 'produccion', 'mantenimiento', 'transporte', 'servicios', 'administracion', 'otros')),
    tipo_gasto TEXT CHECK (tipo_gasto IN ('fijo', 'variable')),
    fecha DATE DEFAULT CURRENT_DATE,
    valor DECIMAL(12, 2) NOT NULL,
    proveedor_id BIGINT REFERENCES proveedores(id),
    medio_pago_id BIGINT REFERENCES medios_pago(id),
    pedido_id BIGINT REFERENCES pedidos(id), -- Opcional, si el gasto está atado a un pedido específico (e.g. domicilio)
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. CUENTAS POR COBRAR
CREATE TABLE cuentas_cobrar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id),
    pedido_id BIGINT REFERENCES pedidos(id),
    fecha_vencimiento DATE,
    valor_total DECIMAL(12, 2) NOT NULL,
    valor_pagado DECIMAL(12, 2) DEFAULT 0,
    saldo DECIMAL(12, 2) GENERATED ALWAYS AS (valor_total - valor_pagado) STORED,
    estado TEXT CHECK (estado IN ('pagado', 'pendiente', 'vencido')) DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. CUENTAS POR PAGAR
CREATE TABLE cuentas_pagar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT REFERENCES proveedores(id),
    concepto TEXT NOT NULL,
    valor DECIMAL(12, 2) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    fecha_vencimiento DATE,
    estado TEXT CHECK (estado IN ('pendiente', 'pagado', 'vencido')) DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initialization Data (Optional)
INSERT INTO medios_pago (nombre, tipo) VALUES 
('Efectivo', 'efectivo'),
('Nequi', 'digital'),
('Daviplata', 'digital'),
('Bancolombia', 'transferencia');
